steps:

- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/GalchenkoAlexander/ch17-hive.git']

# Copying hive files to GCS
- name: 'gcr.io/cloud-builders/gsutil'
  args:
  - 'cp'
  - 'src/main/hive/*'
  - 'gs://${PROJECT_ID}-artifacts/ch17-hive/hive/'

- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
- name: 'gcr.io/cloud-builders/mvn'
  args: ['package']